version: "3"

services:
  employees-app-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: employees-app-server
    ports:
      - 3002:3000
    environment:
      - ENVIRONMENT=production
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_DATABASE=employees
      - DB_USER=root
      - DB_PASSWORD=password
    command: sh -c "npm run db:setup && npm start"
    depends_on:
      # Run healthchecks to ensure services are started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - employees-network
  mysql:
    image: mysql:latest
    container_name: employees-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    # Make sure mysql is running and connected before starting server and running db scripts
    # Basically wait for it to respond to the ping
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - employees-network
  redis:
    image: redis:latest
    container_name: employees-redis
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - employees-network
  employees-app-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: employees-app-client
    ports:
      - "3000:3000"
    depends_on:
      - employees-app-server
    networks:
      - employees-network

networks:
  employees-network:
    driver: bridge
